/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/m0AcrmVaSZI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'

import { useState } from "react"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { login } from "@/gateways/auth"

export function Login() {
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [showInvalidCredentialsAlert, setShowInvalidCredentialsAlert] = useState(false)
  const handleSubmit = async (e:any) => {
    e.preventDefault()
    const response = await login(email,password);
    setShowInvalidCredentialsAlert(!response)
  }
  return (
    <div className="flex items-center justify-center h-screen">
      <form className="mx-auto max-w-sm space-y-6 p-4 sm:p-6 md:p-8" onSubmit={handleSubmit}>
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold">Iniciar sesión</h1>
          <p className="text-muted-foreground">Ingresa tu correo electrónico para acceder a tu cuenta.</p>
        </div>
        {showInvalidCredentialsAlert && (
          <Alert variant="destructive">
            <AlertDescription>Credenciales incorrectas. Por favor, inténtalo de nuevo.</AlertDescription>
          </Alert>
        )}
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Correo electrónico</Label>
            <Input
              id="email"
              type="email"
              placeholder="ejemplo@dominio.com"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Contraseña</Label>
            <Input
              id="password"
              type="password"
              required
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          <div className="flex flex-col sm:flex-row items-center justify-between">
            <div className="flex items-center space-x-2">
              <Checkbox id="remember" defaultChecked />
              <Label htmlFor="remember" className="text-sm text-muted-foreground">
                Recordar sesión
              </Label>
            </div>
            <Link
              href="#"
              className="inline-block text-sm text-primary underline underline-offset-2 mt-2 sm:mt-0"
              prefetch={false}
            >
              ¿Olvidaste tu contraseña?
            </Link>
          </div>
          <Button type="submit" className="w-full">
            Iniciar sesión
          </Button>
        </div>
      </form>
    </div>
  )
}
